server {
    listen 80;

    client_max_body_size 50M;
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/telemetry/ {
        proxy_pass http://telemetry-device:8080/;
    }

    location /api/archive/ {
        proxy_pass http://archive:8080/;
    }

    location /api/signalr/ {
        proxy_pass http://analyzer:8080/;
    }
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
}