server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/telemetry/ {
        proxy_pass http://telemetry-device:8080/;
    }

    location /api/archive/ {
        proxy_pass http://archive:8080/;
    }

    location /api/signalr/ {
        proxy_pass http://analyzer:8080/;
    }
}